---
apiVersion: v1
kind: Service
metadata:
  name: polybesrv
  namespace: development
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: polybe